export const catalog = {
  "NBA": [
    "Boston Celtics",
    "Denver Nuggets",
    "New York Knicks",
    "Dallas Mavericks",
    "Minnesota Timberwolves",
    "Oklahoma City Thunder",
    "Milwaukee Bucks",
    "Phoenix Suns",
    "Miami Heat",
    "Los Angeles Lakers",
    "Golden State Warriors",
    "Cleveland Cavaliers",
    "Atlanta Hawks",
    "Brooklyn Nets",
    "Charlotte Hornets",
    "Chicago Bulls",
    "Detroit Pistons",
    "Indiana Pacers",
    "Los Angeles Clippers",
    "Memphis Grizzlies",
    "New Orleans Pelicans",
    "Orlando Magic",
    "Philadelphia 76ers",
    "Portland Trail Blazers",
    "Sacramento Kings",
    "San Antonio Spurs",
    "Toronto Raptors",
    "Utah Jazz",
    "Washington Wizards",
    "Houston Rockets"
  ],
  "NFL": [
    "Kansas City Chiefs",
    "Buffalo Bills",
    "Baltimore Ravens",
    "Detroit Lions",
    "Philadelphia Eagles",
    "San Francisco 49ers",
    "Cincinnati Bengals",
    "Houston Texans",
    "Green Bay Packers",
    "Dallas Cowboys",
    "Miami Dolphins",
    "Los Angeles Chargers",
    "Arizona Cardinals",
    "Atlanta Falcons",
    "Carolina Panthers",
    "Chicago Bears",
    "Cleveland Browns",
    "Denver Broncos",
    "Indianapolis Colts",
    "Jacksonville Jaguars",
    "Las Vegas Raiders",
    "Los Angeles Rams",
    "Minnesota Vikings",
    "New England Patriots",
    "New Orleans Saints",
    "New York Giants",
    "New York Jets",
    "Pittsburgh Steelers",
    "Seattle Seahawks",
    "Tampa Bay Buccaneers",
    "Tennessee Titans",
    "Washington Commanders"
  ],
  "MLB": [
    "Los Angeles Dodgers",
    "New York Yankees",
    "Atlanta Braves",
    "Houston Astros",
    "Philadelphia Phillies",
    "Baltimore Orioles",
    "Texas Rangers",
    "Seattle Mariners",
    "San Diego Padres",
    "Boston Red Sox",
    "Chicago Cubs",
    "Arizona Diamondbacks",
    "Athletics",
    "Chicago White Sox",
    "Cincinnati Reds",
    "Cleveland Guardians",
    "Colorado Rockies",
    "Detroit Tigers",
    "Kansas City Royals",
    "Los Angeles Angels",
    "Miami Marlins",
    "Milwaukee Brewers",
    "Minnesota Twins",
    "New York Mets",
    "Pittsburgh Pirates",
    "San Francisco Giants",
    "St. Louis Cardinals",
    "Tampa Bay Rays",
    "Toronto Blue Jays",
    "Washington Nationals"
  ],
  "NHL": [
    "Edmonton Oilers",
    "Florida Panthers",
    "New York Rangers",
    "Colorado Avalanche",
    "Dallas Stars",
    "Toronto Maple Leafs",
    "Vegas Golden Knights",
    "Carolina Hurricanes",
    "Boston Bruins",
    "Vancouver Canucks",
    "Tampa Bay Lightning",
    "Winnipeg Jets",
    "Anaheim Ducks",
    "Buffalo Sabres",
    "Calgary Flames",
    "Chicago Blackhawks",
    "Columbus Blue Jackets",
    "Detroit Red Wings",
    "Los Angeles Kings",
    "Minnesota Wild",
    "Montreal Canadiens",
    "Nashville Predators",
    "New Jersey Devils",
    "New York Islanders",
    "Ottawa Senators",
    "Philadelphia Flyers",
    "Pittsburgh Penguins",
    "San Jose Sharks",
    "Seattle Kraken",
    "St. Louis Blues",
    "Utah Mammoth",
    "Washington Capitals"
  ],
  "NCAA Football": [
    "Georgia Bulldogs",
    "Ohio State Buckeyes",
    "Texas Longhorns",
    "Oregon Ducks",
    "Alabama Crimson Tide",
    "Michigan Wolverines",
    "Notre Dame Fighting Irish",
    "LSU Tigers",
    "Penn State Nittany Lions",
    "Tennessee Volunteers",
    "Clemson Tigers",
    "Florida State Seminoles",
    "Air Force",
    "Akron",
    "Appalachian State",
    "Arizona",
    "Arizona State",
    "Arkansas",
    "Arkansas State",
    "Buffalo",
    "BYU",
    "California",
    "Central Michigan",
    "Charlotte",
    "Cincinnati",
    "Coastal Carolina",
    "Colorado",
    "Colorado State",
    "Delaware",
    "Fresno State",
    "Georgia Southern",
    "Georgia State",
    "Georgia Tech",
    "Hawaiʻi",
    "Houston",
    "Illinois",
    "Indiana",
    "Iowa",
    "Iowa State",
    "Louisiana",
    "Louisiana Tech",
    "Louisville",
    "Marshall",
    "Maryland",
    "Memphis",
    "Miami (FL)",
    "Miami (OH)",
    "Nebraska",
    "Nevada",
    "New Mexico",
    "New Mexico State",
    "North Carolina",
    "North Dakota State",
    "North Texas",
    "Northern Illinois",
    "Northwestern",
    "Oregon State",
    "Pittsburgh",
    "Purdue",
    "Rice",
    "Rutgers",
    "Sacramento State",
    "Sam Houston",
    "San Diego State",
    "San Jose State",
    "SMU",
    "TCU",
    "Temple",
    "Texas A&M",
    "Texas State",
    "Texas Tech",
    "Toledo",
    "Troy",
    "Tulane",
    "Tulsa",
    "UAB",
    "Utah State",
    "UTEP",
    "UTSA",
    "Vanderbilt",
    "Virginia",
    "Virginia Tech",
    "Wake Forest",
    "Washington",
    "Washington State",
    "West Virginia",
    "Western Kentucky",
    "Western Michigan",
    "Army",
    "Auburn",
    "Ball State",
    "Baylor",
    "Boise State",
    "Boston College",
    "Bowling Green",
    "Duke",
    "East Carolina",
    "Eastern Michigan",
    "Florida Atlantic",
    "FIU",
    "Florida",
    "Jacksonville State",
    "James Madison",
    "Kansas",
    "Kansas State",
    "Kennesaw State",
    "Kent State",
    "Kentucky",
    "Liberty",
    "Michigan State",
    "Middle Tennessee",
    "Minnesota",
    "Mississippi State",
    "Missouri",
    "Missouri State",
    "Navy",
    "NC State",
    "Ohio",
    "Oklahoma",
    "Oklahoma State",
    "Old Dominion",
    "Ole Miss",
    "South Alabama",
    "South Carolina",
    "South Florida",
    "Southern Miss",
    "Stanford",
    "Syracuse",
    "UCF",
    "UCLA",
    "UConn",
    "ULM",
    "UMass",
    "UNLV",
    "USC",
    "Utah",
    "Wisconsin",
    "Wyoming",
    "Cal Poly",
    "Eastern Washington",
    "Idaho",
    "Idaho State",
    "Montana",
    "Montana State",
    "Northern Arizona",
    "Northern Colorado",
    "Portland State",
    "Southern Utah",
    "UC Davis",
    "Utah Tech",
    "Weber State",
    "Albany",
    "Bryant",
    "Campbell",
    "Elon",
    "Hampton",
    "Maine",
    "Monmouth",
    "New Hampshire",
    "North Carolina A&T",
    "Rhode Island",
    "Sacred Heart",
    "Stony Brook",
    "Towson",
    "Brown",
    "Columbia",
    "Cornell",
    "Dartmouth",
    "Harvard",
    "Penn",
    "Princeton",
    "Yale",
    "Delaware State",
    "Howard",
    "Morgan State",
    "Norfolk State",
    "North Carolina Central",
    "South Carolina State",
    "Illinois State",
    "Indiana State",
    "Murray State",
    "North Dakota",
    "Northern Iowa",
    "South Dakota",
    "South Dakota State",
    "Southern Illinois",
    "Youngstown State",
    "Central Connecticut",
    "Duquesne",
    "LIU",
    "Mercyhurst",
    "New Haven",
    "Robert Morris",
    "Stonehill",
    "Wagner",
    "Charleston Southern",
    "Eastern Illinois",
    "Gardner-Webb",
    "Lindenwood",
    "Southeast Missouri State",
    "Tennessee State",
    "UT Martin",
    "Western Illinois",
    "Bucknell",
    "Colgate",
    "Fordham",
    "Georgetown",
    "Holy Cross",
    "Lafayette",
    "Lehigh",
    "Richmond",
    "Villanova",
    "William & Mary",
    "Butler",
    "Davidson",
    "Dayton",
    "Drake",
    "Marist",
    "Morehead State",
    "Presbyterian",
    "St. Thomas",
    "San Diego",
    "Stetson",
    "Valparaiso",
    "Chattanooga",
    "The Citadel",
    "East Tennessee State",
    "Furman",
    "Mercer",
    "Samford",
    "Tennessee Tech",
    "VMI",
    "Western Carolina",
    "Wofford",
    "East Texas A&M",
    "Houston Christian",
    "Incarnate Word",
    "Lamar",
    "McNeese",
    "Nicholls",
    "Northwestern State",
    "Southeastern Louisiana",
    "Stephen F. Austin",
    "UTRGV",
    "Alabama A&M",
    "Alabama State",
    "Alcorn State",
    "Arkansas-Pine Bluff",
    "Bethune-Cookman",
    "Florida A&M",
    "Grambling State",
    "Jackson State",
    "Mississippi Valley State",
    "Prairie View A&M",
    "Southern",
    "Texas Southern",
    "Abilene Christian",
    "Austin Peay",
    "Central Arkansas",
    "Eastern Kentucky",
    "North Alabama",
    "Tarleton State",
    "West Florida",
    "West Georgia",
    "Merrimack",
    "Chicago State"
  ],
  "NCAA Basketball": [
    "Duke Blue Devils",
    "UConn Huskies",
    "Kansas Jayhawks",
    "North Carolina Tar Heels",
    "Houston Cougars",
    "Kentucky Wildcats",
    "Arizona Wildcats",
    "Purdue Boilermakers",
    "Gonzaga Bulldogs",
    "Baylor Bears",
    "Michigan State Spartans",
    "Villanova Wildcats",
    "Alabama A&M University",
    "Alabama State University",
    "Auburn University",
    "Jacksonville State University",
    "Samford University",
    "Troy University",
    "University of Alabama",
    "University of Alabama at Birmingham",
    "University of North Alabama",
    "University of South Alabama",
    "Arkansas State University",
    "University of Arkansas at Little Rock",
    "University of Arkansas, Fayetteville",
    "University of Arkansas, Pine Bluff",
    "University of Central Arkansas",
    "Arizona State University",
    "Grand Canyon University",
    "Northern Arizona University",
    "California Baptist University",
    "California Polytechnic State University",
    "California State University, Bakersfield",
    "California State University, Fresno",
    "California State University, Fullerton",
    "California State University, Northridge",
    "California State University, Sacramento",
    "Long Beach State University",
    "Loyola Marymount University",
    "Pepperdine University",
    "Saint Mary's College of California",
    "San Diego State University",
    "San Jose State University",
    "Santa Clara University",
    "Stanford University",
    "University of California, Berkeley",
    "University of California, Davis",
    "University of California, Irvine",
    "University of California, Los Angeles",
    "University of California, Riverside",
    "University of California, San Diego",
    "University of California, Santa Barbara",
    "University of San Diego",
    "University of San Francisco",
    "University of Southern California",
    "University of the Pacific",
    "Colorado State University",
    "U.S. Air Force Academy",
    "University of Colorado Boulder",
    "University of Denver",
    "University of Northern Colorado",
    "Central Connecticut State University",
    "Fairfield University",
    "Quinnipiac University",
    "Sacred Heart University",
    "University of New Haven",
    "Yale University",
    "American University",
    "George Washington University",
    "Georgetown University",
    "Howard University",
    "Delaware State University",
    "University of Delaware",
    "Bethune-Cookman University",
    "Florida A&M University",
    "Florida Atlantic University",
    "Florida Gulf Coast University",
    "Florida International University",
    "Florida State University",
    "Jacksonville University",
    "Stetson University",
    "University of Central Florida",
    "University of Florida",
    "University of Miami (Florida)",
    "University of North Florida",
    "University of South Florida",
    "University of West Florida",
    "Georgia Institute of Technology",
    "Georgia Southern University",
    "Georgia State University",
    "Kennesaw State University",
    "Mercer University",
    "University of Georgia",
    "University of West Georgia",
    "University of Hawaii, Manoa",
    "Drake University",
    "Iowa State University",
    "University of Iowa",
    "University of Northern Iowa",
    "Boise State University",
    "Idaho State University",
    "University of Idaho",
    "Bradley University",
    "Chicago State University",
    "DePaul University",
    "Eastern Illinois University",
    "Illinois State University",
    "Loyola University Chicago",
    "Northern Illinois University",
    "Northwestern University",
    "Southern Illinois University at Carbondale",
    "Southern Illinois University Edwardsville",
    "University of Illinois Chicago",
    "University of Illinois Urbana-Champaign",
    "Western Illinois University",
    "Ball State University",
    "Butler University",
    "Indiana State University",
    "Indiana University Indianapolis",
    "Indiana University, Bloomington",
    "Purdue University Fort Wayne",
    "University of Evansville",
    "University of Notre Dame",
    "University of Southern Indiana",
    "Valparaiso University",
    "Kansas State University",
    "Wichita State University",
    "Bellarmine University",
    "Eastern Kentucky University",
    "Morehead State University",
    "Murray State University",
    "Northern Kentucky University",
    "University of Louisville",
    "Western Kentucky University",
    "Grambling State University",
    "Louisiana State University",
    "Louisiana Tech University",
    "LSU New Orleans",
    "McNeese State University",
    "Nicholls State University",
    "Northwestern State University",
    "Southeastern Louisiana University",
    "Southern University, Baton Rouge",
    "Tulane University",
    "University of Louisiana at Lafayette",
    "University of Louisiana Monroe",
    "Boston College",
    "Boston University",
    "College of the Holy Cross",
    "Harvard University",
    "Merrimack College",
    "Northeastern University",
    "Stonehill College",
    "University of Massachusetts Lowell",
    "University of Massachusetts, Amherst",
    "Coppin State University",
    "Loyola University Maryland",
    "Morgan State University",
    "Mount St. Mary's University",
    "Towson University",
    "U.S. Naval Academy",
    "University of Maryland Eastern Shore",
    "University of Maryland, Baltimore County",
    "University of Maryland, College Park",
    "University of Maine",
    "Central Michigan University",
    "Eastern Michigan University",
    "Oakland University",
    "University of Detroit Mercy",
    "University of Michigan",
    "Western Michigan University",
    "University of Minnesota, Twin Cities",
    "University of St. Thomas (Minnesota)",
    "Lindenwood University",
    "Missouri State University",
    "Saint Louis University",
    "Southeast Missouri State University",
    "University of Missouri, Columbia",
    "University of Missouri-Kansas City",
    "Alcorn State University",
    "Jackson State University",
    "Mississippi State University",
    "Mississippi Valley State University",
    "The University of Southern Mississippi",
    "University of Mississippi",
    "Montana State University-Bozeman",
    "University of Montana",
    "Appalachian State University",
    "Campbell University",
    "Davidson College",
    "East Carolina University",
    "Elon University",
    "Gardner-Webb University",
    "High Point University",
    "North Carolina A&T State University",
    "North Carolina Central University",
    "North Carolina State University",
    "Queens University of Charlotte",
    "The University of North Carolina at Charlotte",
    "The University of North Carolina at Greensboro",
    "University of North Carolina Asheville",
    "University of North Carolina Wilmington",
    "Wake Forest University",
    "Western Carolina University",
    "North Dakota State University",
    "University of North Dakota",
    "Creighton University",
    "University of Nebraska at Omaha",
    "University of Nebraska-Lincoln",
    "Dartmouth College",
    "University of New Hampshire",
    "Fairleigh Dickinson University, Metropolitan Campus",
    "Monmouth University",
    "New Jersey Institute of Technology",
    "Princeton University",
    "Rider University",
    "Rutgers, The State University of New Jersey, New Brunswick",
    "Saint Peter's University",
    "Seton Hall University",
    "New Mexico State University",
    "University of New Mexico",
    "University of Nevada, Las Vegas",
    "University of Nevada, Reno",
    "Binghamton University",
    "Canisius University",
    "Colgate University",
    "Columbia University-Barnard College",
    "Cornell University",
    "Fordham University",
    "Hofstra University",
    "Iona University",
    "Le Moyne College",
    "Long Island University",
    "Manhattan University",
    "Marist University",
    "Niagara University",
    "Siena University",
    "St. Bonaventure University",
    "St. John's University (New York)",
    "Stony Brook University",
    "Syracuse University",
    "U.S. Military Academy",
    "University at Albany",
    "University at Buffalo, the State University of New York",
    "Wagner College",
    "Bowling Green State University",
    "Cleveland State University",
    "Kent State University",
    "Miami University (Ohio)",
    "Ohio University",
    "The Ohio State University",
    "University of Akron",
    "University of Cincinnati",
    "University of Dayton",
    "University of Toledo",
    "Wright State University",
    "Xavier University",
    "Youngstown State University",
    "Oklahoma State University",
    "Oral Roberts University",
    "The University of Tulsa",
    "University of Oklahoma",
    "Oregon State University",
    "Portland State University",
    "University of Oregon",
    "University of Portland",
    "Bucknell University",
    "Drexel University",
    "Duquesne University",
    "La Salle University",
    "Lafayette College",
    "Lehigh University",
    "Mercyhurst University",
    "Pennsylvania State University",
    "Robert Morris University",
    "Saint Joseph's University",
    "Temple University",
    "University of Pennsylvania",
    "University of Pittsburgh",
    "Brown University",
    "Bryant University",
    "Providence College",
    "University of Rhode Island",
    "Charleston Southern University",
    "Clemson University",
    "Coastal Carolina University",
    "College of Charleston (South Carolina)",
    "Furman University",
    "Presbyterian College",
    "South Carolina State University",
    "The Citadel",
    "University of South Carolina Upstate",
    "University of South Carolina, Columbia",
    "Winthrop University",
    "Wofford College",
    "South Dakota State University",
    "University of South Dakota",
    "Austin Peay State University",
    "Belmont University",
    "East Tennessee State University",
    "Lipscomb University",
    "Middle Tennessee State University",
    "Tennessee State University",
    "Tennessee Technological University",
    "University of Memphis",
    "University of Tennessee at Chattanooga",
    "University of Tennessee at Martin",
    "University of Tennessee, Knoxville",
    "Vanderbilt University",
    "Abilene Christian University",
    "East Texas A&M University",
    "Houston Christian University",
    "Lamar University",
    "Prairie View A&M University",
    "Rice University",
    "Sam Houston State University",
    "Southern Methodist University",
    "Stephen F. Austin State University",
    "Tarleton State University",
    "Texas A&M University, College Station",
    "Texas A&M University-Corpus Christi",
    "Texas Christian University",
    "Texas Southern University",
    "Texas State University",
    "Texas Tech University",
    "The University of Texas Rio Grande Valley",
    "University of North Texas",
    "University of Texas at Arlington",
    "University of Texas at Austin",
    "University of Texas at El Paso",
    "University of Texas at San Antonio",
    "University of the Incarnate Word",
    "Brigham Young University",
    "Southern Utah University",
    "University of Utah",
    "Utah State University",
    "Utah Tech University",
    "Utah Valley University",
    "Weber State University",
    "George Mason University",
    "Hampton University",
    "James Madison University",
    "Liberty University",
    "Longwood University",
    "Norfolk State University",
    "Old Dominion University",
    "Radford University",
    "University of Richmond",
    "University of Virginia",
    "Virginia Commonwealth University",
    "Virginia Military Institute",
    "Virginia Polytechnic Institute and State University",
    "William & Mary",
    "University of Vermont",
    "Eastern Washington University",
    "Seattle University",
    "University of Washington",
    "Washington State University",
    "Marquette University",
    "University of Wisconsin-Green Bay",
    "University of Wisconsin-Madison",
    "University of Wisconsin-Milwaukee",
    "Marshall University",
    "West Virginia University",
    "University of Wyoming"
  ],
  "UEFA Champions League": [
    "Real Madrid",
    "Manchester City",
    "Bayern Munich",
    "Paris Saint-Germain",
    "Barcelona",
    "Liverpool",
    "Arsenal",
    "Inter Milan",
    "Atletico Madrid",
    "Borussia Dortmund",
    "Juventus",
    "Benfica",
    "AEK Athens",
    "Aston Villa",
    "Bodø/Glimt",
    "Club Brugge",
    "Como",
    "Feyenoord",
    "Fenerbahçe",
    "Galatasaray",
    "LASK",
    "Lens",
    "RB Leipzig",
    "Lille",
    "Manchester United",
    "Napoli",
    "Porto",
    "PSV",
    "Real Betis",
    "Roma",
    "Slovan Bratislava",
    "Sabah",
    "Shakhtar Donetsk",
    "Slavia Praha",
    "Sporting CP",
    "Stuttgart",
    "Villarreal",
    "Viking"
  ],
  "NASCAR": [
    "Hendrick Motorsports",
    "Team Penske",
    "Joe Gibbs Racing",
    "Trackhouse Racing",
    "23XI Racing",
    "Richard Childress Racing",
    "RFK Racing",
    "Legacy Motor Club",
    "Front Row Motorsports",
    "Wood Brothers Racing",
    "Kaulig Racing",
    "Spire Motorsports",
    "Haas Factory Team",
    "Hyak Motorsports",
    "Rick Ware Racing"
  ],
  "Masters Tournament": [
    "Scottie Scheffler",
    "Rory McIlroy",
    "Jon Rahm",
    "Xander Schauffele",
    "Collin Morikawa",
    "Ludvig Aberg",
    "Viktor Hovland",
    "Jordan Spieth",
    "Hideki Matsuyama",
    "Patrick Cantlay",
    "Max Homa",
    "Tommy Fleetwood",
    "Daniel Berger",
    "Akshay Bhatia",
    "Keegan Bradley",
    "Michael Brennan",
    "Jacob Bridgeman",
    "Sam Burns",
    "Angel Cabrera",
    "Brian Campbell",
    "Wyndham Clark",
    "Corey Conners",
    "Fred Couples",
    "Jason Day",
    "Bryson DeChambeau",
    "Nico Echavarria",
    "Harris English",
    "Ethan Fang",
    "Matt Fitzpatrick",
    "Ryan Fox",
    "Sergio Garcia",
    "Ryan Gerard",
    "Chris Gotterup",
    "Max Greyserman",
    "Ben Griffin",
    "Harry Hall",
    "Brian Harman",
    "Tyrrell Hatton",
    "Russell Henley",
    "Jackson Herrington",
    "Nicolai Hojgaard",
    "Rasmus Hojgaard",
    "Brandon Holtz",
    "Mason Howell",
    "Sungjae Im",
    "Casey Jarvis",
    "Dustin Johnson",
    "Zach Johnson",
    "Naoyuki Kataoka",
    "Johnny Keefer",
    "Michael Kim",
    "Si Woo Kim",
    "Kurt Kitayama",
    "Jake Knapp",
    "Brooks Koepka",
    "Fifa Laopakdee",
    "Min Woo Lee",
    "Haotong Li",
    "Shane Lowry",
    "Robert MacIntyre",
    "Matt McCarty",
    "Tom McKibbin",
    "Maverick McNealy",
    "Rasmus Neergaard-Petersen",
    "Alex Noren",
    "Andrew Novak",
    "Jose Maria Olazabal",
    "Carlos Ortiz",
    "Marco Penge",
    "Aldrich Potgieter",
    "Mateo Pulcini",
    "Aaron Rai",
    "Patrick Reed",
    "Kristoffer Reitan",
    "Davis Riley",
    "Justin Rose",
    "Charl Schwartzel",
    "Adam Scott",
    "Vijay Singh",
    "Cameron Smith",
    "J.J. Spaun",
    "Sam Stevens",
    "Sepp Straka",
    "Nick Taylor",
    "Justin Thomas",
    "Sami Valimaki",
    "Bubba Watson",
    "Mike Weir",
    "Danny Willett",
    "Gary Woodland",
    "Cameron Young"
  ]
};

export const inactiveCatalogEntries = {
  "UEFA Champions League": new Set(["Juventus", "Benfica"])
};

