import {draftGuide, scenarioWarnings, scoreComparison} from './roadmap-model.js';
import {seasonPhase,projectedStandings,scoreValue,contributions,outcomeLabel,queueReason} from './product-model.js';
export function productUI(ctx){
 const {e,field,select,option,textArea,formError,button,link,date,leagueUrl,showDialog,closeDialog,mutate,render,navigate,toast}=ctx;
 const state=()=>ctx.state(),league=()=>ctx.league();
 let comparison=[],scenario={},preview=null,watchOnly=false,search='',sportFilter='',eligibleOnly=false,contextId='';
 function scoped(l){const key=state().user.id+':'+l.id;if(contextId!==key){contextId=key;comparison=[];scenario={};preview=null;watchOnly=false;search='';sportFilter='';eligibleOnly=false;}}
 const form=(action,body,label='Save')=>`<form data-form="product" data-kind="${action}">${formError()}${body}<div class="form-footer"><button class="button primary" type="submit">${label}</button></div></form>`;
 const ledger=l=>`<section class="panel"><h2>Scoring history</h2><p class="small muted">Commissioner-entered results. Rules: ${e(l.rulesVersion)}. ${l.scoreUpdatedAt?'Last result update '+date(l.scoreUpdatedAt):'No result changes recorded since this workspace was introduced.'}</p>${(l.scoreLedger||[]).slice(0,50).map(x=>`<article class="ledger-row"><strong>${e(x.team)} · ${x.oldPoints} → ${x.newPoints} pts</strong><p>${e(x.reason)}</p><small>${e(x.actor)} · ${date(x.at)}</small></article>`).join('')||'<p class="section-space">Result updates will appear here with their source and previous score.</p>'}</section>`;
 function editions(l){return `<section class="panel"><h2>Competition editions</h2><p class="small muted">Championship months are estimates until live schedules are connected. Editions and the contender field lock when drafting starts. Placement points and bonuses are unchanged.</p>${l.commissioner&&l.status==='scheduled'?form('editions',l.editions.map((x,i)=>`<fieldset><legend>${e(x.sport)}</legend>${field('edition'+i,'Competition edition',x.name,'text','required minlength="3"')}${field('month'+i,'Estimated championship month',x.endMonth,'month','required min="2026-01" max="2100-12"')}</fieldset>`).join(''),'Save editions'):l.editions.map(x=>`<p class="section-space"><strong>${e(x.name)}</strong><br><span class="muted">Estimated ${e(x.endMonth)}</span></p>`).join('')}</section>`;}
 function discussion(l){const key='loc-discussion:'+state().user.id+':'+l.id;let seen=0;try{seen=Number(localStorage.getItem(key))||0;}catch{}const unread=l.chat.filter(m=>m.at>seen&&m.userId!==state().user.id).length;return `<section class="panel section-space discussion-brief"><div class="section-head"><h2>League conversation</h2>${button('Mark discussion read ('+unread+' new)','product-discussion-read','ghost',unread?'':'disabled')}</div>${l.announcements[0]?'<p class="notice"><strong>Pinned commissioner announcement</strong><br>'+e(l.announcements[0].text)+'</p>':''}<div class="button-row section-space">${link('Discuss the standings',leagueUrl(l),'ghost')}${link('Review a result source',leagueUrl(l,'scoring'),'ghost')}</div></section><div class="settings-grid"><section class="panel"><h2>League discussion</h2><p class="small muted">A permanent home for your league, before and after the draft.</p><div class="chat-list">${l.chat.map(m=>`<article class="chat-message"><div><strong>${e(m.name)}</strong><time>${date(m.at)}</time>${m.origin==='draft'?'<span class="message-origin">Sent during draft</span>':''}</div><p>${e(m.text)}</p></article>`).join('')||'<p>No messages yet. Start the conversation.</p>'}</div>${form('chat',textArea('text','Message your league','','Write a message'),'Send message')}</section><div class="stack"><section class="panel"><h2>Commissioner announcements</h2>${l.announcements.map(a=>`<article class="ledger-row"><strong>${e(a.name)}</strong><p>${e(a.text)}</p><small>${date(a.at)}</small></article>`).join('')||'<p class="small muted">No announcements yet.</p>'}${l.commissioner?form('announcement',textArea('text','New announcement')):''}</section><section class="panel poll-section"><div class="section-head"><div><h2>League polls</h2><p class="small muted">Each poll stays separate from the conversation.</p></div>${l.commissioner?button('Create poll','product-newpoll','primary'):''}</div><div class="poll-list">${l.polls.map(p=>`<article class="poll-card" aria-labelledby="poll-${p.id}"><div class="section-head"><h3 id="poll-${p.id}">${e(p.question)}</h3><span class="pill ${p.closed?'':'live'}">${p.closed?'Closed':'Open'}</span></div>${p.options.map((o,i)=>`<div class="poll-option">${button(`${e(o)} · ${p.counts[i]} votes${p.myVote===i?' · Your vote':''}`,'product-vote','ghost',`data-poll="${p.id}" data-option="${i}" ${p.closed?'disabled':''}`)}</div>`).join('')}${l.commissioner?`<div class="button-row poll-actions">${!p.closed?button('Close poll','product-closepoll','ghost',`data-poll="${p.id}"`):''}${button('Delete poll','product-deletepoll','danger',`data-poll="${p.id}"`)}</div>`:''}</article>`).join('')||'<p class="small muted">No polls yet. Create one to agree on league preferences.</p>'}</div></section></div></div>`;}
 function scoring(l){const active=l.competitionState==='active';return `<div class="stack"><section class="panel"><div class="section-head"><h2>Competition results</h2><span class="badge">${seasonPhase(l)}</span></div><p class="small muted">${l.picks.filter(p=>p.finish!=null||p.override!=null).length}/${l.picks.length} results recorded · Draft ${l.status}. Results stay provisional until the commissioner confirms the season.</p>${l.commissioner&&l.status==='complete'&&active?form('scores',`<input type="hidden" name="revision" value="${l.scoreRevision}"><div class="table-scroll"><table><thead><tr><th>Contender</th><th>Current points</th><th>Final place</th></tr></thead><tbody>${[...l.picks].sort((a,b)=>a.team.sport.localeCompare(b.team.sport)||(a.finish!=null||a.override!=null)-(b.finish!=null||b.override!=null)).map((p,i,rows)=>`${i===0||rows[i-1].team.sport!==p.team.sport?`<tr class="sport-result-heading"><th colspan="3" scope="colgroup">${e(p.team.sport)} · pending first</th></tr>`:''}<tr><td><strong>${e(p.team.name)}</strong><br><small>${e(p.team.sport)} · ${e(l.members.find(m=>m.id===p.userId)?.name)}</small></td><td>${scoreValue(p)}${p.override!=null?' · override':''}</td><td><label class="sr-only" for="result-${p.id}">Final place for ${e(p.team.name)}</label><input id="result-${p.id}" name="result-${p.id}" type="number" min="1" max="32" value="${p.finish??''}" placeholder="Pending"></td></tr>`).join('')}</tbody></table></div><p class="field-help">Only changed places are submitted. Blank means pending. Changing a place replaces any manual override. Use the manual correction form below to override points.</p>${field('reason','Result source / correction reason','','text','required minlength="5" maxlength="500"')}`,'Preview result changes'):l.picks.map(p=>`<div class="ledger-row"><strong>${e(p.team.name)}</strong> · ${outcomeLabel(p)} · ${scoreValue(p)} pts</div>`).join('')||'<p>Results appear after drafting begins.</p>'}</section>${l.commissioner&&l.status==='complete'?`<section class="panel"><h2>Season controls</h2><p class="small muted">Finalization requires a recorded result for every contender and confirmation that all competitions have ended. Archive keeps the final standings read-only.</p><div class="button-row section-space">${active?button('Finalize season','product-finalize','primary'):l.competitionState==='final'?button('Reopen for correction','product-reopen','ghost')+button('Archive season','product-archive','ghost'):''}${!active?button('Create next season','product-renew','primary'):''}</div>${l.finalizationReason?`<p>${e(l.finalizationReason)}</p>`:''}</section>`:''}${l.previousLeagueId?link('Previous season','/leagues/'+l.previousLeagueId+'/standings','ghost'):''}${l.renewedId?link('Next season','/leagues/'+l.renewedId+'/standings','ghost'):''}${ledger(l)}</div>`;}

 function research(l){
  scoped(l);const mine=l.research[state().user.id]||{},guide=draftGuide(l,state().user.id);
  const matches=l.teams.filter(t=>(!sportFilter||t.sport===sportFilter)&&t.name.toLowerCase().includes(search.toLowerCase())&&(!watchOnly||mine[t.id]?.watched)&&(!eligibleOnly||!queueReason(l,state().user.id,t.id)));
  return `<section class="panel"><h2>Contender research</h2><p class="small muted">Search the league catalog. Notes and watchlists are private. Live statistics, injury feeds and predictions are deferred.</p>${form('research-filter',`<div class="form-grid">${field('researchSearch','Search contenders',search,'search')}${select('researchSport','Sport',option('','All sports',sportFilter)+l.sports.map(x=>option(x,x,sportFilter)).join(''))}</div><label class="check-row"><input type="checkbox" name="eligibleOnly" ${eligibleOnly?'checked':''}>Eligible for my open slots only</label>`,'Apply filters')}<div class="button-row section-space">${button(watchOnly?'Show all contenders':'Show watchlist','product-watchfilter','ghost',`aria-pressed="${watchOnly}"`)}${button('Review watched → queue ('+guide.watched.length+')','product-queue-review','primary',guide.watched.length&&l.status!=='complete'?'':'disabled')}${link('Open draft room',leagueUrl(l,'draft'),'ghost')}</div><div class="comparison-tray section-space"><strong>Compare ${comparison.length}/3</strong>${comparison.map(id=>button(e(l.teams.find(t=>t.id===id)?.name)+' ×','product-toggle','ghost',`data-team="${e(id)}"`)).join('')}${button('Compare selected','product-compare','ghost',comparison.length<2?'disabled':'')}</div><p class="small muted section-space">${matches.length} matching contenders</p><div class="research-grid">${l.sports.filter(x=>matches.some(t=>t.sport===x)).map(sport=>`<section><h3>${e(sport)}</h3>${matches.filter(t=>t.sport===sport).map(t=>`<article class="ledger-row"><strong>${e(t.name)}</strong><p class="small muted">${e(queueReason(l,state().user.id,t.id)||'Eligible for your roster')}</p><div class="button-row">${button(mine[t.id]?.watched?'★ Watching':'☆ Watch','product-watch','ghost',`data-team="${e(t.id)}" aria-pressed="${!!mine[t.id]?.watched}"`)}${button(comparison.includes(t.id)?'Remove comparison':'Compare','product-toggle','ghost',`data-team="${e(t.id)}" aria-pressed="${comparison.includes(t.id)}"`)}${button('Private note','product-note','ghost',`data-team="${e(t.id)}"`)}</div></article>`).join('')}</section>`).join('')||'<p>No matching contenders. Broaden your search or turn off filters.</p>'}</div></section>${l.commissioner&&l.status==='scheduled'?`<section class="panel section-space"><h2>Add missing contenders</h2><p class="small muted">Review the field before drafting; new contenders have no inferred statistics.</p>${form('contenders',select('sport','Sport',l.sports.map(s=>option(s,s,'')).join(''))+textArea('names','Contender names, one per line'),'Add contenders')}</section>`:''}`;
 }
 function scenarios(l){
  scoped(l);const warnings=scenarioWarnings(l,scenario),mine=l.picks.filter(p=>p.userId===state().user.id),others=l.picks.filter(p=>p.userId!==state().user.id);
  const controls=picks=>l.sports.filter(s=>picks.some(p=>p.team.sport===s)).map(s=>`<fieldset><legend>${e(s)}</legend>${picks.filter(p=>p.team.sport===s).map(p=>select('scenario-'+p.id,p.team.name+' · '+l.members.find(m=>m.id===p.userId)?.name+' · current '+scoreValue(p)+' pts',option('','Keep current result',scenario[p.id]??'')+Array.from({length:32},(_,i)=>option(i+1,i===0?'Champion · 12 pts':i===1?'Runner-up · 9 pts':'Place '+(i+1)+' · '+Math.max(0,9-i)+' pts',scenario[p.id])).join(''))).join('')}</fieldset>`).join('');
  return `<section class="panel"><h2>What if?</h2><p>Change finishes to compare championship outcomes. Other results remain fixed. This never edits real scores or predicts probabilities.</p>${l.picks.length?form('scenario','<h3 class="section-space">Your contenders</h3>'+controls(mine)+'<details class="disclosure"><summary>Other managers’ contenders</summary>'+controls(others)+'</details>','Calculate scenario'):'<p class="section-space">Draft contenders first to explore championship outcomes.</p>'}<div class="section-space" aria-live="polite">${warnings.map(w=>`<p class="notice">${e(w)}</p>`).join('')}<div class="table-scroll"><table><caption>Current standings compared with your hypothetical finishes</caption><thead><tr><th>Manager</th><th>Current</th><th>Scenario</th><th>Change</th></tr></thead><tbody>${scoreComparison(l,scenario).map(r=>`<tr><th scope="row">${e(r.name)}</th><td>#${r.oldRank} · ${r.before} pts</td><td>#${r.rank} · ${r.total} pts</td><td>${r.delta>=0?'+':''}${r.delta} pts</td></tr>`).join('')}</tbody></table></div></div>${button('Clear scenario','product-clear-scenario','ghost')}</section>`;
 }
 function overview(l){const mine=contributions(l,state().user.id);return `<section class="panel section-space"><h2>Your points by sport</h2><p class="small muted">All bars use the same scale. Select a manager in standings for the full placement and bonus breakdown.</p><div class="contribution-grid section-space">${mine.map(x=>`<div><strong>${x.total} pts</strong><p>${e(x.sport)}</p><meter min="0" max="${Math.max(12,...mine.map(x=>x.total))}" value="${x.total}" aria-label="${e(x.sport)}: ${x.total} points"></meter></div>`).join('')}</div>${link('Trace points to result sources',leagueUrl(l,'scoring'),'ghost')}</section>`;}
 async function action(a,b){if(!a.startsWith('product-'))return false;const l=league();
  if(a==='product-discussion-read'){try{localStorage.setItem('loc-discussion:'+state().user.id+':'+l.id,String(Date.now()));}catch{}render({preserve:true});}
  else if(a==='product-watch'){const n=l.research[state().user.id]?.[b.dataset.team]||{};await mutate('/api/leagues/'+l.id+'/research',{teamId:b.dataset.team,note:n.note||'',watched:!n.watched},()=>render({preserve:true}));}
  else if(a==='product-queue-review'){const items=draftGuide(l,state().user.id).watched;showDialog('Review queue additions',form('queuewatched','<p>Choose contenders to append to your existing queue in the order shown. Reorder them in the draft room after saving. Eligibility is checked again when you save.</p>'+items.map(t=>'<label class="check-row"><input type="checkbox" name="queueTeam" value="'+e(t.id)+'" checked>'+e(t.name)+' · '+e(t.sport)+'</label>').join(''),'Add selected to queue'));}
  else if(a==='product-watchfilter'){watchOnly=!watchOnly;render({preserve:true});}
  else if(a==='product-toggle'){if(comparison.includes(b.dataset.team))comparison=comparison.filter(x=>x!==b.dataset.team);else if(comparison.length<3)comparison.push(b.dataset.team);else toast('Compare up to three contenders.');render({preserve:true});}
  else if(a==='product-compare'){showDialog('Compare contenders',`<div class="table-scroll"><table><thead><tr><th>Contender</th><th>Sport</th><th>Roster eligibility</th><th>Your note</th></tr></thead><tbody>${comparison.map(id=>{const t=l.teams.find(t=>t.id===id);return t?`<tr><td>${e(t.name)}</td><td>${e(t.sport)}</td><td>${e(queueReason(l,state().user.id,id)||'Eligible')}</td><td>${e(l.research[state().user.id]?.[id]?.note||'No note')}</td></tr>`:'';}).join('')}</tbody></table></div><p class="small muted">Statistics and projections are deferred until a sports-data source is connected.</p>`);}
  else if(a==='product-note'){const t=l.teams.find(t=>t.id===b.dataset.team),n=l.research[state().user.id]?.[t.id]||{};showDialog('Research · '+t.name,form('research',`<input type="hidden" name="teamId" value="${e(t.id)}">${textArea('note','Private note',n.note||'')}<label class="check-row"><input type="checkbox" name="watched" ${n.watched?'checked':''}>Watch this contender</label>`));}
  else if(a==='product-clearskipped')await mutate(`/api/leagues/${l.id}/clearskipped`,{},()=>render({preserve:true}));
  else if(a==='product-clear-scenario'){scenario={};render();}
  else if(a==='product-vote'||a==='product-closepoll')await mutate(`/api/leagues/${l.id}/${a==='product-vote'?'vote':'closepoll'}`,{pollId:b.dataset.poll,option:Number(b.dataset.option)},()=>render({preserve:true}));
  else if(a==='product-newpoll')showDialog('Create league poll',form('poll',field('question','Poll question','','text','required minlength="3"')+textArea('options','Options, one per line','','Add 2–8 choices'),'Create poll'));
  else if(a==='product-deletepoll')showDialog('Delete this poll?',form('deletepoll',`<input type="hidden" name="pollId" value="${e(b.dataset.poll)}"><p>This permanently removes the poll and its votes.</p>`,'Delete poll'));
  else if(a==='product-finalize')showDialog('Finalize season',form('finalize',`<p>Confirm every competition is finished. Results will be locked until you explicitly reopen scoring.</p><label class="check-row"><input type="checkbox" name="confirmed" required>All included competitions have ended and I reviewed the results.</label>${field('reason','Final result source / explanation','','text','required minlength="5" maxlength="500"')}`,'Finalize season'));
  else if(a==='product-reopen')showDialog('Reopen scoring',form('reopen',field('reason','Correction reason','','text','required minlength="5" maxlength="500"'),'Reopen season'));
  else if(a==='product-archive')showDialog('Archive final season',form('archive','<p>This preserves the final standings and prevents further scoring changes. You can create a new season from this archive.</p>','Archive season'));
  else if(a==='product-renew')showDialog('Create next season',form('renew',field('name','League name',l.name,'text','required minlength="3"')+field('season','Season',l.season+1,'number','required min="2026" max="2100"')+'<p>Sports and draft settings are copied. Managers must be invited and accept again. Results, messages, and research are not copied.</p>','Create next season'));
  return true;
 }
 async function submit(formEl,data){if(formEl.dataset.form!=='product')return false;const l=league(),kind=formEl.dataset.kind;
  if(kind==='research-filter'){search=data.researchSearch||'';sportFilter=data.researchSport||'';eligibleOnly=!!data.eligibleOnly;render();return true;}
  if(kind==='queuewatched')data={teamIds:new FormData(formEl).getAll('queueTeam')};
  if(kind==='scenario'){scenario={};for(const p of l.picks){const v=data['scenario-'+p.id];if(v!==undefined&&v!=='')scenario[p.id]=Number(v);}render();return true;}
  if(kind==='scores'){const results=l.picks.filter(p=>String(p.finish??'')!==data['result-'+p.id]).map(p=>({pickId:p.id,finish:data['result-'+p.id]}));if(!results.length){toast('Change at least one final place before previewing.');return true;}preview={revision:Number(data.revision),reason:data.reason,results};showDialog('Review result changes',form('applyscores',`<p>${results.length} result changes. These replace placement and bonus points using current rules.</p>${results.map(r=>{const p=l.picks.find(p=>p.id===r.pickId);return `<p class="ledger-row">${e(p.team.name)} · ${scoreValue(p)} → ${scoreValue({...p,finish:r.finish,override:null})} pts</p>`;}).join('')}<h3>Standings impact</h3>${scoreComparison(l,Object.fromEntries(results.map(r=>[r.pickId,r.finish===''?null:Number(r.finish)]))).map(r=>`<p>${e(r.name)} · #${r.oldRank} → #${r.rank} · ${r.before} → ${r.total} pts</p>`).join('')}<p>Source: ${e(data.reason)}</p>`,'Confirm results'));return true;}
  if(kind==='applyscores'){data=preview;}
  if(kind==='editions')data={editions:l.editions.map((x,i)=>({sport:x.sport,name:data['edition'+i],endMonth:data['month'+i],confirmed:false}))};
  if(kind==='research')data.watched=!!data.watched;
  if(kind==='finalize')data.confirmed=!!data.confirmed;
  await mutate(`/api/leagues/${l.id}/${kind==='applyscores'?'scores':kind}`,data,result=>{closeDialog();if(kind==='applyscores'){try{sessionStorage.removeItem('loc-form:'+state().user.id+':'+location.pathname+':product:scores');}catch{}}if(result.createdId)navigate(`/leagues/${result.createdId}/settings`);else render({preserve:true});toast('Saved.');},formEl);return true;
 }
 return {editions,discussion,scoring,research,scenarios,overview,action,submit};
}


