import {seasonPhase,projectedStandings,scoreValue,contributions,outcomeLabel,queueReason} from './product-model.js';
export function productUI(ctx){
 const {e,field,select,option,textArea,formError,button,link,date,leagueUrl,showDialog,closeDialog,mutate,render,navigate,toast}=ctx;
 const state=()=>ctx.state(),league=()=>ctx.league();
 let comparison=[],scenario={},preview=null,practiceStep=0,watchOnly=false,contextId='';
 function scoped(l){const key=state().user.id+':'+l.id;if(contextId!==key){contextId=key;comparison=[];scenario={};preview=null;watchOnly=false;}} 
 const form=(action,body,label='Save')=>`<form data-form="product" data-kind="${action}">${formError()}${body}<div class="form-footer"><button class="button primary" type="submit">${label}</button></div></form>`;
 const ledger=l=>`<section class="panel"><h2>Scoring history</h2><p class="small muted">Commissioner-entered results. Rules: ${e(l.rulesVersion)}. ${l.scoreUpdatedAt?'Last result update '+date(l.scoreUpdatedAt):'No result changes recorded since this workspace was introduced.'}</p>${(l.scoreLedger||[]).slice(0,50).map(x=>`<article class="ledger-row"><strong>${e(x.team)} · ${x.oldPoints} → ${x.newPoints} pts</strong><p>${e(x.reason)}</p><small>${e(x.actor)} · ${date(x.at)}</small></article>`).join('')||'<p class="section-space">Result updates will appear here with their source and previous score.</p>'}</section>`;
 function editions(l){return `<section class="panel"><h2>Competition editions</h2><p class="small muted">Championship months are estimates until live schedules are connected. Editions and the contender field lock when drafting starts. Placement points and bonuses are unchanged.</p>${l.commissioner&&l.status==='scheduled'?form('editions',l.editions.map((x,i)=>`<fieldset><legend>${e(x.sport)}</legend>${field('edition'+i,'Competition edition',x.name,'text','required minlength="3"')}${field('month'+i,'Estimated championship month',x.endMonth,'month','required min="2026-01" max="2100-12"')}</fieldset>`).join(''),'Save editions'):l.editions.map(x=>`<p class="section-space"><strong>${e(x.name)}</strong><br><span class="muted">Estimated ${e(x.endMonth)}</span></p>`).join('')}</section>`;}
 function discussion(l){return `<div class="settings-grid"><section class="panel"><h2>League discussion</h2><p class="small muted">A permanent home for your league, before and after the draft.</p><div class="chat-list">${l.chat.map(m=>`<article class="chat-message"><strong>${e(m.name)}</strong><time>${date(m.at)}</time><p>${e(m.text)}</p></article>`).join('')||'<p>No messages yet. Start the conversation.</p>'}</div>${form('chat',textArea('text','Message your league','','Write a message'),'Send message')}</section><div class="stack"><section class="panel"><h2>Commissioner announcements</h2>${l.announcements.map(a=>`<article class="ledger-row"><strong>${e(a.name)}</strong><p>${e(a.text)}</p><small>${date(a.at)}</small></article>`).join('')||'<p class="small muted">No announcements yet.</p>'}${l.commissioner?form('announcement',textArea('text','New announcement')):''}</section><section class="panel"><h2>League polls</h2>${l.polls.map(p=>`<fieldset><legend>${e(p.question)} ${p.closed?'· Closed':''}</legend>${p.options.map((o,i)=>`<div class="poll-option">${button(`${e(o)} · ${p.counts[i]} votes${p.myVote===i?' · Your vote':''}`,'product-vote','ghost',`data-poll="${p.id}" data-option="${i}" ${p.closed?'disabled':''}`)}</div>`).join('')}${!p.closed&&l.commissioner?button('Close poll','product-closepoll','ghost',`data-poll="${p.id}"`):''}</fieldset>`).join('')||'<p class="small muted">Use polls to agree on league preferences.</p>'}${l.commissioner?form('poll',field('question','Poll question','','text','required minlength="3"')+textArea('options','Options, one per line'),'Create poll'):''}</section></div></div>`;}
 function scoring(l){const active=l.competitionState==='active';return `<div class="stack"><section class="panel"><div class="section-head"><h2>Competition results</h2><span class="badge">${seasonPhase(l)}</span></div><p class="small muted">${l.picks.filter(p=>p.finish!=null||p.override!=null).length}/${l.picks.length} results recorded · Draft ${l.status}. Results stay provisional until the commissioner confirms the season.</p>${l.commissioner&&l.status==='complete'&&active?form('scores',`<input type="hidden" name="revision" value="${l.scoreRevision}"><div class="table-scroll"><table><thead><tr><th>Contender</th><th>Current points</th><th>Final place</th></tr></thead><tbody>${l.picks.map(p=>`<tr><td><strong>${e(p.team.name)}</strong><br><small>${e(p.team.sport)} · ${e(l.members.find(m=>m.id===p.userId)?.name)}</small></td><td>${scoreValue(p)}${p.override!=null?' · override':''}</td><td><label class="sr-only" for="result-${p.id}">Final place for ${e(p.team.name)}</label><input id="result-${p.id}" name="result-${p.id}" type="number" min="1" max="32" value="${p.finish??''}" placeholder="Pending"></td></tr>`).join('')}</tbody></table></div><p class="field-help">Only changed places are submitted. Blank means pending. Changing a place replaces any manual override. Use the manual correction form below to override points.</p>${field('reason','Result source / correction reason','','text','required minlength="5" maxlength="500"')}`,'Preview result changes'):l.picks.map(p=>`<div class="ledger-row"><strong>${e(p.team.name)}</strong> · ${outcomeLabel(p)} · ${scoreValue(p)} pts</div>`).join('')||'<p>Results appear after drafting begins.</p>'}</section>${l.commissioner&&l.status==='complete'?`<section class="panel"><h2>Season controls</h2><p class="small muted">Finalization requires a recorded result for every contender and confirmation that all competitions have ended. Archive keeps the final standings read-only.</p><div class="button-row section-space">${active?button('Finalize season','product-finalize','primary'):l.competitionState==='final'?button('Reopen for correction','product-reopen','ghost')+button('Archive season','product-archive','ghost'):''}${!active?button('Create next season','product-renew','primary'):''}</div>${l.finalizationReason?`<p>${e(l.finalizationReason)}</p>`:''}</section>`:''}${l.previousLeagueId?link('Previous season','/leagues/'+l.previousLeagueId+'/standings','ghost'):''}${l.renewedId?link('Next season','/leagues/'+l.renewedId+'/standings','ghost'):''}${ledger(l)}</div>`;}
 function research(l){scoped(l);const mine=l.research[state().user.id]||{};return `<section class="panel"><h2>Contender research</h2><p class="small muted">Illustrative catalog plus commissioner-added contenders. No live stats, injuries, projections, or performance claims. Notes and watchlists are private to your account.</p><div class="button-row section-space">${button(`Compare selected (${comparison.length}/3)`,'product-compare','primary',comparison.length<2?'disabled':'')}${button(watchOnly?'Show all contenders':'Show watchlist','product-watchfilter','ghost',`aria-pressed="${watchOnly}"`)}${link('Open draft room',leagueUrl(l,'draft'),'ghost')}</div><div class="research-grid section-space">${l.sports.map(s=>`<details class="disclosure"><summary>${e(s)} · ${l.teams.filter(t=>t.sport===s).length} contenders</summary>${l.teams.filter(t=>t.sport===s&&(!watchOnly||mine[t.id]?.watched)).map(t=>`<article class="ledger-row"><strong>${e(t.name)}</strong><p class="small muted">${e(queueReason(l,state().user.id,t.id)||'Eligible for your roster')}${mine[t.id]?.watched?' · Watching':''}</p><div class="button-row">${button(comparison.includes(t.id)?'Remove comparison':'Compare','product-toggle','ghost',`data-team="${e(t.id)}" aria-pressed="${comparison.includes(t.id)}"`)}${button('Notes & watch','product-note','ghost',`data-team="${e(t.id)}"`)}</div></article>`).join('')}</details>`).join('')}</div></section>${l.commissioner&&l.status==='scheduled'?`<section class="panel section-space"><h2>Add missing contenders</h2><p class="small muted">Check the competition field before drafting. Manually added entries have no inferred statistics and are appended after the illustrative catalog in timeout order.</p>${form('contenders',select('sport','Sport',l.sports.map(s=>option(s,s,'')).join(''))+textArea('names','Contender names, one per line'),'Add contenders')}</section>`:''}`;}
 function scenarios(l){scoped(l);return `<section class="panel"><h2>What if?</h2><p>Explore hypothetical finishes using the existing placement points and bonuses. This never changes real results and does not predict sporting outcomes.</p>${form('scenario',l.picks.map(p=>field('scenario-'+p.id,`${e(p.team.name)} · current ${scoreValue(p)} pts`,scenario[p.id]??'','number','min="1" max="32"','Blank preserves the current result.')).join(''),'Calculate scenario')}<div class="section-space" aria-live="polite">${projectedStandings(l,scenario).map(r=>{const original=l.standings.find(x=>x.id===r.id);return `<p class="ledger-row"><strong>#${r.rank} ${e(r.name)}</strong> · ${r.total} pts (${r.total-(original?.total||0)>=0?'+':''}${r.total-(original?.total||0)} from current)</p>`;}).join('')}</div>${button('Clear scenario','product-clear-scenario','ghost')}</section>`;}
 function overview(l){const mine=contributions(l,state().user.id),updates=l.scoreLedger.slice(0,3);return `<section class="panel section-space"><div class="section-head"><h2>Your championship briefing</h2><span class="badge">${seasonPhase(l)}</span></div><p class="small muted">${l.status==='complete'?'Follow results across your roster. All updates are entered by your commissioner.':'Prepare your roster: one contender per sport. Review the editions and build your private research shortlist.'}</p><div class="button-row section-space">${link('Research contenders',leagueUrl(l,'research'),'ghost')}${link('What-if calculator',leagueUrl(l,'scenarios'),'ghost')}${button('Practice the rules','product-practice','ghost')}</div><details class="disclosure"><summary>Your next steps · rules-based guide</summary><p>${l.status==='scheduled'?'Review competition editions, invite managers, then prepare a queue for every sport.':l.status==='complete'?l.competitionState==='active'?'Review pending results and the scoring ledger. Use What if? to explore how remaining finishes affect your rank.':'Review the final standings. Your commissioner can create the next season without losing this archive.':'Check your open roster slots. Put multiple eligible contenders in your queue for each unfilled sport.'}</p><p class="small muted">This guide uses your league state and LOC rules. It is not AI or a sports prediction.</p></details><div class="contribution-grid section-space">${mine.map(x=>`<div><strong>${x.total} pts</strong><p>${e(x.sport)}</p><meter min="0" max="${Math.max(12,...mine.map(x=>x.total))}" value="${x.total}" aria-label="${e(x.sport)} contribution: ${x.total} points"></meter></div>`).join('')}</div>${updates.map(x=>`<p class="ledger-row">${e(x.team)}: ${x.oldPoints} → ${x.newPoints} pts · ${e(x.reason)}</p>`).join('')||'<p class="small muted section-space">No recorded score changes yet. Results are provisional until finalized.</p>'}<details class="disclosure"><summary>Recorded standings snapshots (${l.scoreHistory.length})</summary>${l.scoreHistory.slice(-10).reverse().map(x=>`<p class="ledger-row">${date(x.at)} · ${x.rows.map(r=>`#${r.rank} ${e(l.members.find(m=>m.id===r.id)?.name)} ${r.total} pts`).join(' · ')}</p>`).join('')||'<p>Snapshots start with the next recorded result; past rankings are not reconstructed.</p>'}</details></section>`;}
 function practice(){showDialog('Practice LOC · '+(practiceStep+1)+' of 3',`<p>${['Draft one contender in each sport. Each contender belongs to only one manager. Snake order reverses each round.','Practice pick confirmed. Your queue is a priority list. At timeout, LOC chooses the first eligible entry; filled sports and drafted contenders are skipped.','Practice backup queued. A champion earns 9 placement points + 3 bonus = 12. Runner-up earns 8 + 1 = 9. Other places earn max(0, 10 − place). Totals determine rank; equal totals share rank.'][practiceStep]}</p><p class="small muted">Practice only. Your leagues and picks stay unchanged.</p>${practiceStep===0?button('Draft a practice contender','product-practice-next','primary'):practiceStep===1?button('Add an eligible backup to the practice queue','product-practice-next','primary'):button('Finish practice','product-practice-next','primary')}`);}
 async function action(a,b){if(!a.startsWith('product-'))return false;const l=league();
  if(a==='product-practice'){practiceStep=0;practice();}
  else if(a==='product-practice-next'){if(practiceStep<2){practiceStep++;practice();}else closeDialog();}
  else if(a==='product-watchfilter'){watchOnly=!watchOnly;render({preserve:true});}
  else if(a==='product-toggle'){if(comparison.includes(b.dataset.team))comparison=comparison.filter(x=>x!==b.dataset.team);else if(comparison.length<3)comparison.push(b.dataset.team);else toast('Compare up to three contenders.');render({preserve:true});}
  else if(a==='product-compare'){showDialog('Compare contenders',`<div class="table-scroll"><table><thead><tr><th>Contender</th><th>Sport</th><th>Roster eligibility</th><th>Your note</th></tr></thead><tbody>${comparison.map(id=>{const t=l.teams.find(t=>t.id===id);return t?`<tr><td>${e(t.name)}</td><td>${e(t.sport)}</td><td>${e(queueReason(l,state().user.id,id)||'Eligible')}</td><td>${e(l.research[state().user.id]?.[id]?.note||'No note')}</td></tr>`:'';}).join('')}</tbody></table></div><p class="small muted">Statistics and projections are deferred until a sports-data source is connected.</p>`);}
  else if(a==='product-note'){const t=l.teams.find(t=>t.id===b.dataset.team),n=l.research[state().user.id]?.[t.id]||{};showDialog('Research · '+t.name,form('research',`<input type="hidden" name="teamId" value="${e(t.id)}">${textArea('note','Private note',n.note||'')}<label class="check-row"><input type="checkbox" name="watched" ${n.watched?'checked':''}>Watch this contender</label>`));}
  else if(a==='product-clearskipped')await mutate(`/api/leagues/${l.id}/clearskipped`,{},()=>render({preserve:true}));
  else if(a==='product-clear-scenario'){scenario={};render();}
  else if(a==='product-vote'||a==='product-closepoll')await mutate(`/api/leagues/${l.id}/${a==='product-vote'?'vote':'closepoll'}`,{pollId:b.dataset.poll,option:Number(b.dataset.option)},()=>render({preserve:true}));
  else if(a==='product-finalize')showDialog('Finalize season',form('finalize',`<p>Confirm every competition is finished. Results will be locked until you explicitly reopen scoring.</p><label class="check-row"><input type="checkbox" name="confirmed" required>All included competitions have ended and I reviewed the results.</label>${field('reason','Final result source / explanation','','text','required minlength="5" maxlength="500"')}`,'Finalize season'));
  else if(a==='product-reopen')showDialog('Reopen scoring',form('reopen',field('reason','Correction reason','','text','required minlength="5" maxlength="500"'),'Reopen season'));
  else if(a==='product-archive')showDialog('Archive final season',form('archive','<p>This preserves the final standings and prevents further scoring changes. You can create a new season from this archive.</p>','Archive season'));
  else if(a==='product-renew')showDialog('Create next season',form('renew',field('name','League name',l.name,'text','required minlength="3"')+field('season','Season',l.season+1,'number','required min="2026" max="2100"')+'<p>Sports and draft settings are copied. Managers must be invited and accept again. Results, messages, and research are not copied.</p>','Create next season'));
  return true;
 }
 async function submit(formEl,data){if(formEl.dataset.form!=='product')return false;const l=league(),kind=formEl.dataset.kind;
  if(kind==='scenario'){scenario={};for(const p of l.picks){const v=data['scenario-'+p.id];if(v!=='')scenario[p.id]=Number(v);}render();return true;}
  if(kind==='scores'){const results=l.picks.filter(p=>String(p.finish??'')!==data['result-'+p.id]).map(p=>({pickId:p.id,finish:data['result-'+p.id]}));if(!results.length){toast('Change at least one final place before previewing.');return true;}preview={revision:Number(data.revision),reason:data.reason,results};showDialog('Review result changes',form('applyscores',`<p>${results.length} result changes. These replace placement and bonus points using current rules.</p>${results.map(r=>{const p=l.picks.find(p=>p.id===r.pickId);return `<p class="ledger-row">${e(p.team.name)} · ${scoreValue(p)} → ${scoreValue({...p,finish:r.finish,override:null})} pts</p>`;}).join('')}<p>Source: ${e(data.reason)}</p>`,'Confirm results'));return true;}
  if(kind==='applyscores'){data=preview;}
  if(kind==='editions')data={editions:l.editions.map((x,i)=>({sport:x.sport,name:data['edition'+i],endMonth:data['month'+i],confirmed:false}))};
  if(kind==='research')data.watched=!!data.watched;
  if(kind==='finalize')data.confirmed=!!data.confirmed;
  await mutate(`/api/leagues/${l.id}/${kind==='applyscores'?'scores':kind}`,data,result=>{closeDialog();if(kind==='applyscores'){try{sessionStorage.removeItem('loc-form:'+state().user.id+':'+location.pathname+':product:scores');}catch{}}if(result.createdId)navigate(`/leagues/${result.createdId}/settings`);else render({preserve:true});toast('Saved.');},formEl);return true;
 }
 return {editions,discussion,scoring,research,scenarios,overview,action,submit};
}
