import {draftGuide, championshipCalendar, championshipImpact} from './roadmap-model.js';

export function roadmapUI({e,link,button,date,leagueUrl,state}) {
  // Capture visit baselines once; polling must not turn unseen changes into read changes.
  const baselines = new Map();
  function briefing(l) {
    const uid=state().user.id, key=`loc-visit:${uid}:${l.id}`;
    if(!baselines.has(key)) {let at=0;try{at=Number(localStorage.getItem(key))||0;localStorage.setItem(key,String(Date.now()));}catch{}baselines.set(key,at);}
    const since=baselines.get(key), updates=(l.scoreLedger||[]).filter(x=>x.at>since), guide=draftGuide(l,uid), impact=championshipImpact(l,uid);
    const last=(l.scoreHistory||[]).slice(-2)[0]?.rows.find(r=>r.id===uid), current=l.standings.find(r=>r.id===uid);
    return `<section class="panel section-space"><div class="section-head"><h2>${l.status==='complete'?'Your season briefing':'Your draft assistant'}</h2><span class="badge">Rules-based</span></div>${l.status==='complete'?`<p class="section-space"><strong>${impact.gap===0?'You share or hold the lead':impact.gap+' points behind the leader'}</strong>${last&&l.scoreHistory.length>1?` · Rank ${last.rank} → ${current.rank} since the previous recorded update`:''}.</p><p class="small muted">${since?updates.length+' result changes since your last visit on this device.':'Your first visit on this device. Here are the latest recorded results.'}</p>${updates.slice(0,3).map(x=>`<p class="ledger-row">${e(x.team)} · ${x.oldPoints} → ${x.newPoints} pts · ${date(x.at)}</p>`).join('')}${link('Review result sources',leagueUrl(l,'scoring'),'ghost')}<details class="disclosure"><summary>Championship impact · conditional outcomes</summary><p class="small muted">Each row changes only that contender to champion and holds all other results fixed. These are arithmetic scenarios, not probabilities or guaranteed paths to victory.</p>${impact.options.map(x=>`<p class="ledger-row">If ${e(x.pick.team.name)} wins: ${x.points} total points (+${x.delta}), rank #${x.rank}.</p>`).join('')||'<p>No pending contenders in your roster.</p>'}${link('Build a combined scenario',leagueUrl(l,'scenarios'),'primary')}</details>`:`<p class="section-space">${guide.open.length} open sport slots · ${guide.queue.length} eligible queued contenders.</p><p>${guide.uncovered.length?'Add queue coverage for '+e(guide.uncovered.join(', '))+'.':'Every open sport has queue coverage. Order your preferences before the draft.'}</p><p class="small muted">${guide.watched.length} eligible watched contenders can be added from Research. Queue order expresses your preferences; catalog order is not a prediction.</p><div class="button-row section-space">${link('Prepare my queue',leagueUrl(l,'draft'),'primary')}${link('Review watchlist',leagueUrl(l,'research'),'ghost')}</div>`}</section>`;
  }
  function calendar(l) {
    return `<section class="panel section-space"><h2>Your championship calendar</h2><p class="small muted">Estimated championship months from your league editions. Commissioner-entered dates are not live schedules.</p>${l.scheduled?`<p class="ledger-row"><strong>Draft · ${date(l.scheduled)}</strong> · ${l.status==='scheduled'?'Scheduled; commissioner starts the room':'Draft '+e(l.status)}</p>`:''}<div class="calendar-grid">${championshipCalendar(l,state().user.id).map(x=>`<article class="ledger-row"><span class="badge">Estimated ${e(x.endMonth)}</span><h3>${e(x.name)}</h3><p>${x.contenders.map(p=>`${e(p.name)} · ${p.pending?'Result pending':p.points+' pts'}`).join('<br>')||'No contender drafted yet'}</p></article>`).join('')}</div>${link('Review competition editions',leagueUrl(l,'rules'),'ghost')}</section>`;
  }
  function tour(l) {return l.sample?`<section class="panel sample-tour"><h2>Explore your sample championship</h2><p>All managers, messages, results and history here are fictional. Try these three steps:</p><ol><li>${link('1. Inspect the rosters',leagueUrl(l,'roster'),'ghost')} · one contender per sport.</li><li>${link('2. Follow the point breakdown',leagueUrl(l,'scoring'),'ghost')} · placement + championship bonus.</li><li>${link('3. Try a different finish',leagueUrl(l,'scenarios'),'ghost')} · see how it changes the table.</li></ol></section>`:'';}
  return {briefing,calendar,tour};
}
